# Generated by Django 4.0.4 on 2022-06-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfs', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
