# Generated by Django 4.0.4 on 2022-06-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='pdfs',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
