# Generated by Django 4.0.4 on 2022-06-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_uploadedimage_pdfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
